# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have high level overview of PCA as well as some of the details in the algorithm itself, its time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the Data

To start, import the data stored in the file 'foodusa.csv'.

In [1]:
#Your code here
import pandas as pd
import numpy as np
df = pd.read_csv('foodusa.csv')
df.head()

City  Bread  Burger  Milk  Oranges  Tomatoes
0    ATLANTA   24.5    94.5  73.9     80.1      41.6
1  BALTIMORE   26.5    91.0  67.5     74.6      53.3
2     BOSTON   29.7   100.8  61.4    104.0      59.6
3    BUFFALO   22.8    86.6  65.3    118.4      51.2
4    CHICAGO   26.7    86.7  62.7    105.9      51.2

In [6]:
# Drop city since it won't be needed
df.drop('City', axis = 1, inplace = True)

## Normalize the Data

Next, normalize your data by subtracting the feature mean from each of the columns

In [2]:
#Your code here
for column in df.columns[1:]:
    df[column] = df[column] - df[column].mean()

In [4]:
df.mean()

Bread      -9.267949e-16
Burger     -8.032222e-15
Milk        2.780385e-15
Oranges     1.235726e-14
Tomatoes   -5.869701e-15
dtype: float64

## Calculate the Covariance Matrix

The next step for PCA is to calculate to covariance matrix for your normalized data. Do so here.

In [8]:
#Your code here
cov = np.cov(df.T)
cov

array([[  6.2844664 ,  12.91096838,   5.71905138,   1.31037549,
          7.28513834],
       [ 12.91096838,  57.07711462,  17.50752964,  22.69187747,
         36.29478261],
       [  5.71905138,  17.50752964,  48.30588933,  -0.27503953,
         13.44347826],
       [  1.31037549,  22.69187747,  -0.27503953, 202.75628458,
         38.76241107],
       [  7.28513834,  36.29478261,  13.44347826,  38.76241107,
         57.80055336]])

## Calculate the Eigenvectors

Next, calculate the eigenvectors for your covariance matrix.

In [9]:
#Your code here
w,v = np.linalg.eig(cov)

## Sorting the Eigenvectors to Determine Primary Components

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues!

In [14]:
#Your code here
w_sorted_ind = np.argsort(w)
v_sorted = v[:,np.flip(w_sorted_ind)]
print(v)
print(w)
print(v_sorted)

[[-0.02848905 -0.16532108 -0.96716354 -0.18972574  0.02135748]
 [-0.2001224  -0.63218494  0.24877074 -0.65862454  0.25420475]
 [-0.0416723  -0.44215032  0.03606094  0.10765906 -0.88874949]
 [-0.93885906  0.31435473 -0.01521357 -0.06904699 -0.12135003]
 [-0.27558389 -0.52791603 -0.03429221  0.71684022  0.36100184]]
[218.99867893  91.72316894   3.02922934  20.81054128  37.66268981]
[[-0.02848905 -0.16532108  0.02135748 -0.18972574 -0.96716354]
 [-0.2001224  -0.63218494  0.25420475 -0.65862454  0.24877074]
 [-0.0416723  -0.44215032 -0.88874949  0.10765906  0.03606094]
 [-0.93885906  0.31435473 -0.12135003 -0.06904699 -0.01521357]
 [-0.27558389 -0.52791603  0.36100184  0.71684022 -0.03429221]]


## Reprojecting the Data

Finally, reproject the dataset using your eigenvectors. Reproject the dataset down to 2 dimensions.

In [15]:
#Your code here
reduced = v_sorted[0:2].dot(df.T).T
reduced

array([[ 11.10636706,  14.73134932],
       [  1.21900301,  21.44989411],
       [-12.29365615,  -4.73286484],
       [ -4.27410508,  -4.95746329],
       [ -2.08570219,   1.77071529],
       [  2.02322957,  -4.83130671],
       [  0.76513968,  -5.78241861],
       [  5.01990281,  -7.08302707],
       [ -5.28963606,  -7.18560259],
       [-20.29491244, -21.8073279 ],
       [  6.65984778,   1.94000258],
       [  6.31128707,   2.48929146],
       [ 14.12127203,  10.53050299],
       [ -6.30360841,  -4.25846371],
       [ -2.70119271,  -4.22170394],
       [-17.39101398, -11.4694373 ],
       [-11.5197783 ,   7.50279463],
       [ -3.85046231, -12.11400365],
       [  0.02742717,  -9.57890292],
       [ 16.08930141,   7.15585369],
       [  7.92495397,   0.76667379],
       [  8.40796253,  16.30333807],
       [  6.32837355,  13.38210659]])

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further application of PCA.